vaadin:
  launch-browser: true
spring:
  application:
    name: catering
  jpa:
    hibernate:
      ddl-auto: create-drop
  docker:
    compose:
      file: docker-compose.yml
  datasource:
    url: 'jdbc:postgresql://localhost:5432/catering'
    username: 'catering'
    password: 'secret'
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

        format_sql: true